Shop/ServiceHost/Areas/Administrator/Pages/Shop/ProductCategory/Index.cshtml.cs
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sm.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administrator.Pages.Shop.ProductCategory
{
    // [Authorize(Roles = "1, 3")]
    public class Index : PageModel
    {
        private readonly IProductCategoryApplication _productCategoryApplication;
        public List<ProductCategoryViewModel> productCategories;
        public ProductCategorySearchModel SearchModel;
        public EditProductCategory productCategory;

        public Index(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }

        public void OnGet(ProductCategorySearchModel searchModel)
        {
            productCategories = _productCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var res = _productCategoryApplication.Create(command);
            return new JsonResult(res);
        }

        public IActionResult OnGetEdit(long id)
        {
            productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("./Edit", productCategory);
        }

        public JsonResult OnPostEdit(EditProductCategory command)
        {
            if (ModelState.IsValid)
            {
                // do something
                // this is for validation
            }
            
            var res = _productCategoryApplication.Edit(command);
            return new JsonResult(res);
        }
    }
}

Shop/ServiceHost/Areas/Administrator/Pages/Shop/Products/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shop.Infrastructure;
using Sm.Application.Contracts.Product;
using Sm.Application.Contracts.ProductCategory;
using Sm.Configuration.Permissions;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Products
{
    public class Index : PageModel
    {
        [TempData]
        public string Message { get; set; }
        
        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _categoryApplication;
        public SelectList Categories;
        public List<ProductViewModel> products;
        public ProductSearchModel SearchModel;

        
        public Index(IProductApplication productApplication, IProductCategoryApplication categoryApplication)
        {
            _productApplication = productApplication;
            _categoryApplication = categoryApplication;
        }
        
        [NeedsPermission(ShopPermission.ListProducts)]
        public void OnGet(ProductSearchModel searchModel)
        {
            Categories = new SelectList(_categoryApplication.GetCategories(), "Id", "Name");
            products = _productApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProduct
            {
                Categories = _categoryApplication.GetCategories()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProduct command)
        {
            var res = _productApplication.Create(command);
            return new JsonResult(res);
        }

        public IActionResult OnGetEdit(long id)
        {
            var product = _productApplication.GetDetails(id);
            product.Categories = _categoryApplication.GetCategories(); 
            return Partial("./Edit", product);
        }

        public JsonResult OnPostEdit(EditProduct command)
        {
            var res = _productApplication.Edit(command);
            return new JsonResult(res);
        }

    }
}

Shop/ServiceHost/Areas/Administrator/Pages/Shop/ProductsPicture/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sm.Application.Contracts.Product;
using Sm.Application.Contracts.ProductPicture;

namespace ServiceHost.Areas.Administrator.Pages.Shop.ProductsPicture
{
    public class Index : PageModel
    {
        [TempData]
        public string Message { get; set; }
        
        private readonly IProductPictureApplication _productPictureApplication;
        private readonly IProductApplication _productApplication;
        public SelectList Products;
        public List<ProductPictureViewModel> pictures;
        public ProductPictureViewModel SearchModel;


        public Index(IProductApplication productApplication, IProductPictureApplication productPictureApplication)
        {
            _productApplication = productApplication;
            _productPictureApplication = productPictureApplication;
        }

        public void OnGet(ProductPictureSearchModel searchModel)
        {
            Products = new SelectList(_productApplication.GetProducts(), "Id", "Name");
            pictures = _productPictureApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProductPicture()
            {
                Products = _productApplication.GetProducts()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProductPicture command)
        {
            var res = _productPictureApplication.Create(command);
            return new JsonResult(res);
        }

        public IActionResult OnGetEdit(long id)
        {
            var PictureDetails = _productPictureApplication.GetDetails(id);
            PictureDetails.Products = _productApplication.GetProducts(); 
            return Partial("./Edit", PictureDetails);
        }

        public JsonResult OnPostEdit(EditProductPicture command)
        {
            var res = _productPictureApplication.Edit(command);
            return new JsonResult(res);
        }

        public IActionResult OnGetRemove(long id)
        {
            var res = _productPictureApplication.Remove(id);
            if (res.IsSuccedded)
                return RedirectToPage("./index");

            Message = res.Message;
            return RedirectToPage("./index");

        }
        public IActionResult OnGetRestore(long id)
        {
            var res = _productPictureApplication.Restore(id);
            if (res.IsSuccedded)
                return RedirectToPage("./index");

            Message = res.Message;
            return RedirectToPage("./index");
        }
    }
}

Shop/ServiceHost/Areas/Administrator/Pages/Shop/Sliders/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sm.Application.Contracts.Product;
using Sm.Application.Contracts.ProductPicture;
using Sm.Application.Contracts.Slider;

namespace ServiceHost.Areas.Administrator.Pages.Shop.Sliders
{
    public class Index : PageModel
    {
        [TempData]
        public string Message { get; set; }
        
        private readonly ISliderApplication _sliderApplication;
        public List<SliderViewModel> sliders;


        public Index(ISliderApplication sliderApplication)
        {
            _sliderApplication = sliderApplication;
        }

        public void OnGet()
        {
            sliders = _sliderApplication.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateSlider();

            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateSlider command)
        {
            var res = _sliderApplication.Create(command);
            return new JsonResult(res);
        }

        public IActionResult OnGetEdit(long id)
        {
            var sliderDetails = _sliderApplication.GetDetails(id);
            return Partial("./Edit", sliderDetails);
        }

        public JsonResult OnPostEdit(EditSlider command)
        {
            var res = _sliderApplication.Edit(command);
            return new JsonResult(res);
        }

        public IActionResult OnGetRemove(long id)
        {
            var res = _sliderApplication.Remove(id);
            if (res.IsSuccedded)
                return RedirectToPage("./index");

            Message = res.Message;
            return RedirectToPage("./index");

        }
        public IActionResult OnGetRestore(long id)
        {
            var res = _sliderApplication.Restore(id);
            if (res.IsSuccedded)
                return RedirectToPage("./index");

            Message = res.Message;
            return RedirectToPage("./index");
        }
    }
}

Shop/ServiceHost/Areas/Administrator/Pages/Shop/ProductsPicture/Create.cshtml
@model Sm.Application.Contracts.ProductPicture.CreateProductPicture


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد محصول جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">Picture</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">گروه محصول</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="0">گروه محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        
        
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

Shop/ServiceHost/Areas/Administrator/Pages/Shop/ProductsPicture/Edit.cshtml
@model Sm.Application.Contracts.ProductPicture.EditProductPicture


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش محصول @Model.Picture </h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">Picture file</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Picture Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">گروه محصول</label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products, "Id", "Name")'>
                        <option value="0">گروه محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">Picture Title</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>

        <input type="hidden" asp-for="Id" value="@Model.Id">
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

Shop/ServiceHost/Areas/Administrator/Pages/Shop/ProductsPicture/Index.cshtml
@page
@model ServiceHost.Areas.Administrator.Pages.Shop.ProductsPicture.Index

@{
    Layout = "_Admin_Layout";
    ViewData["title"] = "مدیریت محصولات";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد محصول جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در محصولات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="Model.Products">
                            <option value="0">گروه محصولی ...</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست تساویر ()</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>عکس</th>
                                <th>نام</th>
                                <th>گروه</th>
                                <th>تاریخ تولید</th>
                                <th>عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach(var picture in Model.pictures)
                            {
                                <tr>
                                    <td>@picture.Id</td>
                                    <td>
                                        <img src="~/productCategories/@picture.Picture" style="height: 70px; width: 70px;"/>
                                    </td>
                                    <td>@picture.ProductId</td>
                                    <td>@picture.Product</td>
                                    <td>@picture.CreationDate</td>
                                    <td>
                                        <a class="btn btn-warning waves-effect waves-light m-b-5"
                                           href="#showmodal=@Url.Page("./index", "Edit", new {Id = picture.Id})">
                                            <i class="fa fa-edit"></i> ویرایش
                                        </a>
                                        @if (picture.IsRemoved)
                                        {
                                            <a class="btn btn-danger btn-sm waves-effect waves-light" asp-page="./index" asp-page-handler="Restore" asp-route-id="@picture.Id">ناموجود شود</a>                                            
                                        }
                                        else
                                        {
                                            <a class="btn btn-success btn-sm waves-effect waves-light" asp-page="./index" asp-page-handler="Remove" asp-route-id="@picture.Id">موجود شود</a>
                                        }
                                        
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatable').dataTable();
        });
    </script>
}