Shop/ServiceHost/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Shop/ServiceHost/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShopQuery;
using ShopQuery.Contracts.ArticleCategory;
using ShopQuery.Contracts.ProductCategory;

namespace ServiceHost.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IArticleCategoryQuery _articleCategoryQuery;
        private readonly IProductCategoryQuery _productCategoryQuery;

        public MenuViewComponent(IArticleCategoryQuery articleCategoryQuery, IProductCategoryQuery productCategoryQuery)
        {
            _articleCategoryQuery = articleCategoryQuery;
            _productCategoryQuery = productCategoryQuery;
        }

        public IViewComponentResult Invoke()
        {
            var model = new MenuModel
            {
                ProductCategories = _productCategoryQuery.GetCategories(),
                ArticleCategories = _articleCategoryQuery.GetCategories()
            };
            
            
            return View(model);
        }
    }
}

Shop/ServiceHost/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["title"] - Lampshapde Store</title>
    <meta name="keywords" content="@ViewData["keywords"]">
    <meta name="description" content="@ViewData["metadescription"]">

    <!-- Vendor CSS -->
    <link href="~/Theme/assets/css/vendors.css" rel="stylesheet">
    <!-- Main CSS -->
    <link href="~/Theme/assets/css/style.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Theme/assets/css/Custom.css" rel="stylesheet">
</head>

<body>
@await Component.InvokeAsync("Menu");

@RenderBody()



<!--====================  footer area ====================-->
@await Component.InvokeAsync("Footer");
<!--====================  End of footer area  ====================-->

<div class="search-overlay" id="search-overlay">
    <a href="javascript:void(0)" class="close-search-overlay" id="close-search-overlay">
        <i class="ion-ios-close-empty"></i>
    </a>

    <!--=======  search form  =======-->

    <div class="search-form">
        <form method="get" asp-page="Search">
            <input name="value" id="value" type="search" placeholder="Search entire store here ...">
            <button type="submit">
                <i class="ion-android-search"></i>
            </button>
        </form>
    </div>

    <!--=======  End of search form  =======-->
</div>


<!-- scroll to top  -->
<div id="scroll-top">
    <span>Back to top</span><i class="ion-chevron-right"></i><i class="ion-chevron-right"></i>
</div>
<!-- end of scroll to top -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<!-- Vendor JS -->
<script src="~/Theme/assets/js/vendors.js"></script>

<!-- Active JS -->
<script src="~/Theme/assets/js/active.js"></script>
<script src="~/Theme/assets/js/plugins.js"></script>
<script src="~/Theme/assets/js/custom.js"></script>




</body>

</html>